---
collections:
  - name: community.general
    version: "11.4.9"
  - name: ansible.posix
    version: "2.2.1"
  - name: community.docker
  - name: community.vmware
    version: "5.10.0"
  - name: vmware.vmware
