---
podman_systemd_action: "present"
podman_systemd_allowed_actions:
  - present
  - started
  - restarted
  - stopped
  - absent

podman_systemd_unit_name: ""
podman_systemd_description: "Podman kube service {{ podman_systemd_unit_name }}"
podman_systemd_manifest_path: ""
podman_systemd_scope: "system"
podman_systemd_quadlet_dir: >-
  {{
    '/etc/containers/systemd'
    if podman_systemd_scope == 'system'
    else ansible_env.HOME ~ '/.config/containers/systemd'
  }}
podman_systemd_quadlet_path: "{{ podman_systemd_quadlet_dir }}/{{ podman_systemd_unit_name }}.kube"
podman_systemd_service_name: "{{ podman_systemd_unit_name }}.service"
podman_systemd_enabled: true
podman_systemd_state: "started"
podman_systemd_remove_quadlet: true
podman_systemd_install_wanted_by: "multi-user.target"
podman_systemd_after:
  - network-online.target
podman_systemd_wants:
  - network-online.target
