---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: net_vlan_autogen
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          net_vlan_autogen:
            ansible_connection: docker
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
