---
galaxy_info:
  role_name: ansible_remote_tmp
  namespace: lit
  author: Lightning IT
  description: Bootstrap and enforce Ansible remote module temporary directory permissions.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.18"

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - ansible
    - bootstrap
    - tmp

dependencies: []
