---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Use a dedicated workdir for this scenario
    tf_runner_workdir: "/tmp/molecule-tf-runner-basic"

  tasks:
    - name: "Ensure Terraform working directory exists for test"
      ansible.builtin.file:
        path: "{{ tf_runner_workdir }}"
        state: directory
        mode: "0750"

    - name: "Copy test main.tf into workdir"
      ansible.builtin.copy:
        src: "files/main.tf"
        dest: "{{ tf_runner_workdir }}/main.tf"
        mode: "0640"

    - name: "Run lit.foundational.tf_runner against the basic config"
      ansible.builtin.include_role:
        name: "lit.foundational.tf_runner"
      vars:
        tf_runner_clean_state: true
        tf_runner_skip_apply: false
        tf_runner_vars: {}
