---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false

platforms:
  - name: localhost
    address: localhost

provisioner:
  name: ansible
  inventory:
    hosts:
      localhost:
        ansible_connection: local
  config_options:
    defaults:
      host_key_checking: false
      retry_files_enabled: false

scenario:
  name: tf_runner_basic
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
