---
dependency:
  name: shell
  command: ":"

driver:
  name: docker

platforms:
  - name: hetzner_installimage
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      hetzner_installimage:
        ansible_connection: docker
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml

scenario:
  name: hetzner-installimage-basic
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
